Enhance actions by merging json files + creating release

diff --git a/.github/workflows/validate_json.yml b/.github/workflows/validate_json.yml
--- a/.github/workflows/validate_json.yml
+++ b/.github/workflows/validate_json.yml
@@ -1,4 +1,4 @@
-name: Validate JSON marshalling
+name: Validate JSON marshalling and processing
 on: 
   pull_request:
     branches: [main]
@@ -11,3 +11,24 @@ jobs:
         uses: RaaLabs/validate-json@v1.0.1
         with:
           directory: "."
+  validate-json-merge:
+    runs-on: ubuntu-latest
+    needs: validate-json
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        # Most recent Python version as of 2024-12-29.
+        with:
+          python-version: '3.13'
+      # Code does not have dependencies. Otherwise, would need a step here to `pip install` stuff.
+      - name: Execute merge parsing script.
+        run: python .scripts/parse_release.py
+      - name: Verify existence of output file.
+        run: |
+          if [ ! -f iso_3166_data.json ]; then
+            echo "ERROR: Output json not found!"
+            exit 1  # Exit with an error if the file does not exist
+          else
+            echo "OK: Output JSON exists."
+          fi
